routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



Auth::routes();

Route::get('/home', function(){
    return redirect('/');
});
Route::group(['middleware'=>['auth']],function(){
    Route::get('/', 'Admin\DashboardController@index');
    Route::get('/dashboard', 'Admin\DashboardController@index');

    /*
     * Sagar
     **/

    Route::resource('/customer','Admin\CustomerController');//customer's main page
    Route::get('/forcedeletecustomer/{customerid}','Admin\CustomerController@forcedeletecustomer');//customer's hard delete
    Route::get('/deletedcustomers','Admin\CustomerController@deletedCustomer');//customer deleted list page
    Route::get('/restorecustomer/{customerid}','Admin\CustomerController@restoreCustomer');//restoreing the deleted data using id from restore page to index page

    /*
     * end sagar code
     **/


    /*
     * rojina
     **/

    Route::resource('/supplier','Admin\SupplierController');//displays supplier's landing page

    /* Payment started*/
    Route::resource('/payment','Admin\PaymentController');//displays payment landing page

    Route::get('/payment/add/{supplier}','Admin\PaymentController@addInfo');// For listingform  regarding payment method based on supplier_id

    Route::get('/payment/mtdenable/{supplier}','Admin\PaymentController@mtdEnable');// For listing enabling payment method by passing supplier's id

    Route::get('/deletedpayment/{supplier}','Admin\PaymentController@deletedPayMethod');// For  listing temporarily deleted  payment method of the given supplier

    Route::get('/restorepayment/{paymentid}','Admin\PaymentController@restorePayMethod');//To  listing restored  payment method details once deleted//

    Route::get('/forcedeletepaymtd/{paymentid}','Admin\PaymentController@forceDelete');//To delete the payment method that is soft deleted once

    /* Payment ended*/
    /*Invoice start*/

    Route::resource('/invoice','Admin\InvoiceController');//displays invoice's landing page
    Route::get('/deletedinvoices','Admin\InvoiceController@deletedInvoices');//invoice deleted page
    Route::get('/deletedinvoicesinformation/{invoiceid}','Admin\InvoiceController@showdeletedInvoice');//Invoice deleted detail page
    Route::get('/restoredeletedinvoice/{invoiceid}','Admin\InvoiceController@restoreDeletedInvoice');//To restore deleted invoice
    Route::get('/forcedeletedinvoice/{invoiceid}','Admin\InvoiceController@forceDeleted');//To delete invoice permanently
    Route::get('/paidinvoices','Admin\InvoiceController@index');

    /*Invoice ended*/

    /*Product started*/
    Route::resource('/product','Admin\ProductController');//displays product main page
    Route::get('/deletedproducts','Admin\ProductController@deletedProduct');//product deleted page
    Route::get('/restoreproduct/{productid}','Admin\ProductController@restoreProduct');//For restoring the deleted products soft deleted  before
    Route::delete('/forcedeletedproduct/{productid}','Admin\ProductController@forceDelete');//For deleting product permanently
    Route::get('/product/p-enable/{productid}','Admin\ProductController@productEnable');//To enable product status that was disabled before
    Route::get('/product/p-disable/{productid}','Admin\ProductController@productDisable');//To disable product status that was enabled before

    /*Product ended*/

    /*Payamount Started*/
    Route::resource('/payamount','Admin\PayamountController');
    Route::get('/addpayamount/{invoiceid}','Admin\PayamountController@enterAmount');


    /* print invoice */
    Route::get('print-invoice/{invoiceid}', "Admin\InvoiceController@printInvoice");

    /*pdf generator*/
    Route::get('/downloadpdf/{invoiceid}',"Admin\InvoiceController@generatePdf");
    Route::get('/invoice-sendmail/{invoiceid}',"Admin\InvoiceController@sendInvoiceMail");//send mail with invoice pdf attached

    Route::get('/changepassword','Admin\DashboardController@changePassword');
    Route::post('/updatepassword','Admin\DashboardController@updatePassword')->name('password.update');

    /*
     * end rojina code
     * */



});

app/Http/Controllers/Admin/SupplierController.php
<?php

namespace App\Http\Controllers\Admin;
/*
 * coded by:rojina 
 * date:8th august
 *
 * */

use App\Http\Requests\StoreSupplierRequest;
use App\Model\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

class SupplierController extends Controller
{
//    private $supplierRepo;
//    public function  __construct(\SupplierRepository $supplierRepo){
//        $this->supplierRepo=$supplierRepo;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $suppliers=$this->supplierRepo->index();
        $suppliers=Supplier::orderBy('id','DESC')->get();
       return view('admin.supplier.index',compact('suppliers'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSupplierRequest $request)
    {

//        $this->supplierRepo->store($request->toArray());

        $supplier=Supplier::create(Input::all());
        if(Input::hasFile('logo')){
            $image=  Input::file('logo');
            $imageName=  \Illuminate\Support\Str::random('32').'.'.$image->getClientOriginalExtension();
            //now save the image file
            $image->move('images/supplier',$imageName);
            $supplier->logo=$imageName;
        }
        Session::flash("suplier","New Supplier Added Successfully");
        $supplier->save();
        return redirect('/supplier');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier=Supplier::where('status',1)->where('id',$id)->first();
        return view('admin.supplier.detail')
            ->with('supplier',$supplier);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier=Supplier::where('id',$id)->first();
        return view('admin.supplier.edit')
            ->with('supplier',$supplier);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreSupplierRequest $request, $id)
    {
        $supplier=Supplier::find($id);
        $supplier->update(Input::all());
//        dd($supplier);
        if(Input::hasFile('logo')){
            $image=  Input::file('logo');
            $imageName=  \Illuminate\Support\Str::random('32').'.'.$image->getClientOriginalExtension();
            //now save the image file
            $image->move('images/supplier',$imageName);
            $supplier->logo=$imageName;
        }
        $supplier->save();
        Session()->flash("supplier","Supplier Update Successfully");
        return redirect('/supplier');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier=Supplier::find($id);
        $supplier->delete();
        Session()->flash("supplier","Supplier Deleted Successfully");
        return redirect('/supplier');
    }
}

resources/views/admin/supplier/create.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')


  <div class="page-title">
    <div class="pull-left">
      <h3>Add Supplier</h3>
    </div>

    <div class="pull-right">
      <a href="{{route('supplier.index')}}" class="btn btn-primary pull-right">List Suppliers</a>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>

  <div class="clearfix"></div>
  @if($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach($errors->all() as $error)
          <li>{{$error}}</li>
        @endforeach
      </ul>
    </div>
  @endif
  <form class="form-horizontal form-label-left" action="{{route('supplier.store')}}" method="POST" enctype="multipart/form-data">
    {{csrf_field()}}
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="x_panel">
          <div class="x_title">
            <h2>Supplier's Details</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6">Supplier Name *</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="text" class="form-control" name="supplier_name" data-inputmask="'mask': '99/99/9999'" required>
                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6">ABN *</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="text" class="form-control" name="abn" data-inputmask="'mask': '99/99/9999'"  value="{{old('abn')}}"  required >
                <span class="fa fa-key form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6"> Website</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="text" class="form-control" name="website" data-inputmask="'mask': '99/99/9999'" >
                <span class="fa fa-globe form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6"> Logo*</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="file" class="form-control" name="logo" id="logo" data-inputmask="'mask': '99/99/9999'"  value="{{old('logo')}}" required>
                <span class="fa fa-image form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>


          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="x_panel">
          <div class="x_title">
            <h2>Contact Details</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6">Email *</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="email" class="form-control" name="email"  id="email" data-inputmask="'mask': '99/99/9999'" value="{{old('email')}}" required>
                <span class="fa fa-envelope form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 1 *</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="text" class="form-control" name="phone1"  id="phone1"data-inputmask="'mask': '99/99/9999'" value="{{old('phone1')}}" required >
                <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 2</label>
              <div class="col-md-8 col-sm-8 col-xs-6">
                <input type="text" class="form-control" name="phone2" id="phone2" data-inputmask="'mask': '99/99/9999'" >
                <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Address</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <form class="form-horizontal form-label-left input_mask">
              <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                <label for="street">Street *</label>
                <input type="text" class="form-control" name="street" id="street"  value="{{old('street')}}" required>
                <span class="fa fa-map-marker form-control-feedback right" aria-hidden="true"></span>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                <label for="city">City *</label>
                <input type="text" class="form-control" name="city" id="city" value="{{old('city')}}" required>
                <span class="fa fa-location-arrow form-control-feedback right" aria-hidden="true"></span>
              </div>
              <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                <label for="state">State *</label>
                <select class="form-control" name="state"   required>
                  <option value="NSW" @if(old('state')=='NSW')selected @endif> NSW</option>
                  <option value="VIC" @if(old('state')=='VIC')selected @endif>VIC</option>
                  <option value="QLD" @if(old('state')=='QLD')selected @endif>QLD</option>
                  <option value="ACT" @if(old('state')=='ACT')selected @endif>ACT</option>
                  <option value="SA" @if(old('state')=='SA')selected @endif>SA</option>
                  <option value="NT" @if(old('state')=='NT')selected @endif>NT</option>
                  <option value="WA" @if(old('state')=='WA')selected @endif>WA</option>
                </select>
              </div>
              <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                <label for="">Zip Code *</label>
                <input type="text" class="form-control"  name="zip_code" id="zip_code" required>
                <span class="fa fa-file-archive-o form-control-feedback right" aria-hidden="true"></span>
              </div>
              <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                <label for="country">Country *</label>
                <select class="form-control" name="country" required>
                  <option value="Australia" @if(old('country')=="Australia") selected @endif>Australia</option>
                  <option value="Nepal" @if(old('country')=="Nepal") selected @endif>Nepal</option>

                </select>
              </div>





            </form>
          </div>
        </div>
        <div class="x_panel">
          <div class="x_content">

            <div class="col-md-12 col-sm-12 col-xs-12" align="center">
              <button type="submit" class="btn btn-success">Submit</button>
              <button type="reset" class="btn btn-default">Reset</button>
              <a href="{{route('supplier.index')}}" class="btn btn-danger">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </form>
@stop

resources/views/admin/supplier/detail.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    <div class="page-title">
        <div class="page-title col-md-12">
            <div class="pull-left">
                <h3>{{ucfirst($supplier->supplier_name)}}</h3>
            </div>

            <div class="pull-right">
                <a href="{{route('supplier.index')}}" class="btn btn-primary pull-right">List Suppliers</a>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>



        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Supplier's Details</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />

                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Supplier Name:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                {{$supplier->supplier_name}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">ABN:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                {{$supplier->abn}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Website:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                {{$supplier->website}}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Logo: </label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <img src="{{asset('images/supplier/'.$supplier->logo)}}" alt="{{$supplier->supplier_name}}" class="img img-responsive" style="max-width: 200px; border: 1px solid #a5a5a5">
                            </div>
                        </div> </div>

                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Contact Details</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />

                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Email:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                {{$supplier->email}}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 1:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                {{$supplier->phone1}}
                            </div>
                        </div>
                    </div>

                   <div class="row">
                       <div class="form-group">
                           <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 2:</label>
                           <div class="col-md-8 col-sm-8 col-xs-6">
                               {{$supplier->phone2==null?'-':$supplier->phone2}}
                           </div>
                       </div>
                   </div>

                </div>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Address</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                        <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">Street Address: </label>
                            {{$supplier->street}}
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">City</label>
                            {{$supplier->city}}
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="state">State: </label>
                            {{$supplier->state}}

                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">Zip Code: </label>
                            {{$supplier->zip_code}}
                        </div>

                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="country">Country:</label>
                            {{$supplier->country}}

                        </div>
                </div>
            </div>

            {{-- <div class="col-md-12 col-sm-9 col-xs-12 " align="center">

                <a href="" class="btn btn-default">View Invoices</a>

            </div> --}}

    </div>

    </div>
@stop

resources/views/admin/supplier/edit.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    <div class="page-title">
        <div class="pull-left">
            <h3>Edit Supplier</h3>
        </div>

        <div class="pull-right">
            <a href="{{route('supplier.index')}}" class="btn btn-primary pull-right">List Suppliers</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
    @if($errors->any())
        <ul class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    @endif
    <form class="form-horizontal form-label-left" action="{{route('supplier.update',[$supplier->id])}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
        <input type="hidden" name="_method" value="PATCH">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Supplier's Details</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Supplier Name *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="supplier_name" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->supplier_name}}" required>
                                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">ABN *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="abn" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->abn}}" required>
                                <span class="fa fa-key form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Website</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="website" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->website}}">
                                <span class="fa fa-globe form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Logo </label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="file" class="form-control" name="logo" id="logo" data-inputmask="'mask': '99/99/9999'" >
                                <span class="fa fa-image form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Contact Details</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Email *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="email" class="form-control" name="email" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->email}}" required>
                                <span class="fa fa-envelope form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 1 *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="phone1" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->phone1}}" required >
                                <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Phone Number 2</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="phone2" data-inputmask="'mask': '99/99/9999'" value="{{$supplier->phone2}}">
                                <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Address</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">Street Address *</label>
                            <input type="text" class="form-control" name="street" id="inputSuccess3" value="{{$supplier->street}}"  required>
                            <span class="fa fa-map-marker form-control-feedback right" aria-hidden="true"></span>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">City *</label>
                            <input type="text" class="form-control" name="city" id="inputSuccess3" value="{{$supplier->city}}" required>
                            <span class="fa fa-location-arrow form-control-feedback right" aria-hidden="true"></span>
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="state">State *</label>
                            <select class="form-control" name="state" required>
                                <option value="NSW" {{$supplier->state=="NSW"?'selected':''}}>NSW</option>
                                <option value="VIC" {{$supplier->state=="VIC"?'selected':''}}>VIC</option>
                                <option value="QLD" {{$supplier->state=="QLD"?'selected':''}}>QLD</option>
                                <option value="ACT" {{$supplier->state=="ACT"?'selected':''}}>ACT</option>
                                <option value="SA" {{$supplier->state=="SA"?'selected':''}}>SA</option>
                                <option value="NT" {{$supplier->state=="NT"?'selected':''}}>NT</option>
                                <option value="WA" {{$supplier->state=="WA"?'selected':''}}>WA</option>
                            </select>
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="">Zip Code *</label>
                            <input type="text" class="form-control" name="zip_code" id="zip_code" value="{{$supplier->zip_code}}" required>
                            <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
                        </div>

                        <div class="col-md-2 col-sm-6 col-xs-12 form-group has-feedback">
                            <label for="country">Country *</label>
                            <select class="form-control" name="country" required>
                                <option value="Australia" {{$supplier->country=='Australia'?'selected':''}}>Australia</option>
                                <option value="Nepal" {{$supplier->country=='Nepal'?'selected':''}}>Nepal</option>
                            </select>
                        </div>




                    </div>
                </div>
            </div>
            <div class="x_panel">
                <div class="x_content">

                    <div class="col-md-12 col-sm-12 col-xs-12" align="center">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                        <a href="{{route('supplier.index')}}" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
            </div>
        </div>

    </form>
@stop