routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



Auth::routes();

Route::get('/home', function(){
    return redirect('/');
});
Route::group(['middleware'=>['auth']],function(){
    Route::get('/', 'Admin\DashboardController@index');
    Route::get('/dashboard', 'Admin\DashboardController@index');

    /*
     * Sagar
     **/

    Route::resource('/customer','Admin\CustomerController');//customer's main page
    Route::get('/forcedeletecustomer/{customerid}','Admin\CustomerController@forcedeletecustomer');//customer's hard delete
    Route::get('/deletedcustomers','Admin\CustomerController@deletedCustomer');//customer deleted list page
    Route::get('/restorecustomer/{customerid}','Admin\CustomerController@restoreCustomer');//restoreing the deleted data using id from restore page to index page

    /*
     * end sagar code
     **/


    /*
     * rojina
     **/

    Route::resource('/supplier','Admin\SupplierController');//displays supplier's landing page

    /* Payment started*/
    Route::resource('/payment','Admin\PaymentController');//displays payment landing page

    Route::get('/payment/add/{supplier}','Admin\PaymentController@addInfo');// For listingform  regarding payment method based on supplier_id

    Route::get('/payment/mtdenable/{supplier}','Admin\PaymentController@mtdEnable');// For listing enabling payment method by passing supplier's id

    Route::get('/deletedpayment/{supplier}','Admin\PaymentController@deletedPayMethod');// For  listing temporarily deleted  payment method of the given supplier

    Route::get('/restorepayment/{paymentid}','Admin\PaymentController@restorePayMethod');//To  listing restored  payment method details once deleted//

    Route::get('/forcedeletepaymtd/{paymentid}','Admin\PaymentController@forceDelete');//To delete the payment method that is soft deleted once

    /* Payment ended*/
    /*Invoice start*/

    Route::resource('/invoice','Admin\InvoiceController');//displays invoice's landing page
    Route::get('/deletedinvoices','Admin\InvoiceController@deletedInvoices');//invoice deleted page
    Route::get('/deletedinvoicesinformation/{invoiceid}','Admin\InvoiceController@showdeletedInvoice');//Invoice deleted detail page
    Route::get('/restoredeletedinvoice/{invoiceid}','Admin\InvoiceController@restoreDeletedInvoice');//To restore deleted invoice
    Route::get('/forcedeletedinvoice/{invoiceid}','Admin\InvoiceController@forceDeleted');//To delete invoice permanently
    Route::get('/paidinvoices','Admin\InvoiceController@index');

    /*Invoice ended*/

    /*Product started*/
    Route::resource('/product','Admin\ProductController');//displays product main page
    Route::get('/deletedproducts','Admin\ProductController@deletedProduct');//product deleted page
    Route::get('/restoreproduct/{productid}','Admin\ProductController@restoreProduct');//For restoring the deleted products soft deleted  before
    Route::delete('/forcedeletedproduct/{productid}','Admin\ProductController@forceDelete');//For deleting product permanently
    Route::get('/product/p-enable/{productid}','Admin\ProductController@productEnable');//To enable product status that was disabled before
    Route::get('/product/p-disable/{productid}','Admin\ProductController@productDisable');//To disable product status that was enabled before

    /*Product ended*/

    /*Payamount Started*/
    Route::resource('/payamount','Admin\PayamountController');
    Route::get('/addpayamount/{invoiceid}','Admin\PayamountController@enterAmount');


    /* print invoice */
    Route::get('print-invoice/{invoiceid}', "Admin\InvoiceController@printInvoice");

    /*pdf generator*/
    Route::get('/downloadpdf/{invoiceid}',"Admin\InvoiceController@generatePdf");
    Route::get('/invoice-sendmail/{invoiceid}',"Admin\InvoiceController@sendInvoiceMail");//send mail with invoice pdf attached

    Route::get('/changepassword','Admin\DashboardController@changePassword');
    Route::post('/updatepassword','Admin\DashboardController@updatePassword')->name('password.update');

    /*
     * end rojina code
     * */



});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

/*
 * coded by:Rojina
 * date    :13th August
 *
 *
 */

use App\Http\Requests\ProductRequest;
use App\Model\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Validation\Rules\In;
use Illuminate\Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the product.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=Product::orderBy('id',"DESC")->get();
        return view('admin.product.index')
            ->with('products',$products);
    }

    /**
     * Show the form for creating a new product.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        for($i=0;$i<count(Input::get('name'));$i++)
        {
            if(Input::get('name')[$i]!='' || (Input::get('name')[$i]!=null)){
                Product::create([
                    'name'=>Input::get('name')[$i]
                ]);
            }
        }
        Session()->flash('product',"Added Product Successfully");
        return redirect('/product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::where('id',$id)->first();
        return view('admin.product.edit')
            ->with('product',$product);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $product=Product::find($id);
        $product->update(Input::all());
        Session()->flash('product',"Updated Products Successfully");
        return redirect('/product');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product=Product::find($id);
        $product->delete();
        Session()->flash('product',"Deleted Products Successfully");
        return redirect('deletedproducts');
    }

    /* send the deleted data to trash for further use(not deleting directly)*/

    public function deletedProduct()
    {
       $products=Product::onlyTrashed()->get();
        return view('admin.product.deletedproduct')
            ->with('products',$products);

    }
    /*
     *
     *
     * Restore the products that were deleted previously
     */

    public function restoreProduct($productid)
    {
        $product=Product::onlyTrashed()->find($productid);
        $product->restore();
        Session()->flash('product',"Restored Product Successfully");
        return redirect('/deletedproducts');

    }
    /*
     * to delete permanently from the list of products that were soft deleted
     *
     */

    public  function forceDelete($productid)
    {
        $product = Product::onlyTrashed()->find($productid);
        $product->forceDelete();
        Session()->flash('product', "Permanently Deleted Successfully !!!");
        return redirect('/deletedproducts');
    }

   public function productEnable($id)
   {
       $product=Product::find($id);
       $product->status=1;
       $product->save();
       Session()->flash('product',"Choosen Product Activated");
       return redirect('/product');

   }
    public  function productDisable($id)
    {
        $product=Product::find($id);
        $product->status=0;
        $product->save();
        Session()->flash('product',"Choosen Product Deactivated");
        return redirect('/product');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')


    <div class="page-title">
        <div class="pull-left">
            <h3>Add Product</h3>
        </div>

        <div class="pull-right">
            <a href="{{route('product.index')}}" class="btn btn-primary pull-right">List Products</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="clearfix"></div>
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form class="form-horizontal form-label-left" action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">

                    <div class="x_content">
                        <br />


                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th></th>
                                <th>SN</th>
                                <th>Product(s)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr >
                                <td></td>
                                <td>1</td>
                                <td >
                                    <div class="form-group">
                                        <div class="col-md-12 col-sm-12 col-xs-12 product_name">
                                            <input type="text" class="form-control" name="name[]" data-inputmask="'mask': '99/99/9999'"  value="{{old('name[]')}}" required>
                                            <span class="fa fa-product-hunt form-control-feedback right" aria-hidden="true"></span>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr class="row-product hidden" id="rp">
                                <td ><a href="javascript:void(0)" onclick="removeRow(this)"><i class="fa fa-trash-o" ></i></a></td>
                                <td class="increase"></td>
                                <td>
                                    <div class="form-group">
                                        <div class="col-md-12 col-sm-12 col-xs-12 product_name">
                                            <input type="text" class="form-control" name="name[]" data-inputmask="'mask': '99/99/9999'"  value="{{old('name[]')}}"disabled required>
                                            <span class="fa fa-product-hunt form-control-feedback right" aria-hidden="true"></span>
                                        </div>
                                    </div>
                                </td>
                            </tr>

                            </tbody>
                        </table>

                    </div>

                    <button type="button" class="btn btn-success" style="float:right" id="adding_newrow">Add New Row</button>
                </div>



                <div class="x_panel">
                    <div class="x_content">

                        <div class="col-md-12 col-sm-12 col-xs-12" align="center">
                            <button type="submit" class="btn btn-success">Submit</button>
                            <button type="reset" class="btn btn-default">Reset</button>
                            <a href="{{route('product.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
@section('custom-script')
    <script src="{{asset('js/custom.js')}}"></script>
@stop
@stop

resources/views/admin/product/deletedproduct.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    

    <div class="">
        <div class="page-title">
            <div class="pull-left">
                <h3>List Deleted Product</h3>
            </div>

            <div class="pull-right ">
                <a href="{{route('product.index')}}" class="btn btn-primary pull-right">List products</a>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

        <div class="clearfix"></div>
        @if(\Illuminate\Support\Facades\Session::has('product'))
            <div class="alert alert-success text-center col-md-12" id="status">
                {{\Illuminate\Support\Facades\Session::get('product')}}
            </div>
        @endif
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>All products</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>Name</th>

                                <th>Status</th>
                                <th>Action(s)</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->name}}</td>

                                    <td>
                                        @if($product->status==1)
                                            <span class="label label-success">Active</span>
                                        @else
                                            <span class="label label-danger">Inactive</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{url('restoreproduct/'.$product->id)}}" class="btn btn-xs btn-default pull-left" title="Restore product" onclick="return confirm('{{\App\Constant\Constant::RESTORE_ITEM}}')"><i class="fa fa-undo"></i></a>
                                        <form action="{{url('forcedeletedproduct/'.$product->id)}}" method="POST" class="pull-left">
                                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('{{\App\Constant\Constant::DELETE_PERMANENT}}')"><i class="fa fa-trash-o" title="Delete"></i></button>
                                        </form>
                                        <div class="clearfix"></div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>



@stop

resources/views/admin/product/edit.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')


    <div class="page-title">
        <div class="pull-left">
            <h3>Edit Product</h3>
        </div>

        <div class="pull-right">
            <a href="{{route('product.index')}}" class="btn btn-primary pull-right">List Products</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="clearfix"></div>
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form class="form-horizontal form-label-left" action="{{route('product.update',['id'=>$product->id])}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
        <input type="hidden" name="_method" value="PATCH">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">

                    <div class="x_content">
                        <br />


                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>SN</th>
                                <th>Product(s)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr >

                                <td>{{$product->id}}</td>
                                <td >
                                    <div class="form-group">
                                        <div class="col-md-12 col-sm-12 col-xs-12 product_name">
                                            <input type="text" class="form-control" name="name" data-inputmask="'mask': '99/99/9999'" value="{{$product->name}}" required>
                                            <span class="fa fa-product-hunt form-control-feedback right" aria-hidden="true"></span>
                                        </div>
                                    </div>
                                </td>
                            </tr>


                            </tbody>
                        </table>

                    </div>
                </div>



                <div class="x_panel">
                    <div class="x_content">

                        <div class="col-md-12 col-sm-12 col-xs-12" align="center">
                            <button type="submit" class="btn btn-success">Update</button>
                            <button type="reset" class="btn btn-default">Reset</button>
                            <a href="{{route('product.index')}}" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
@section('custom-script')
    <script src="{{asset('js/custom.js')}}"></script>
@stop
@stop

resources/views/admin/product/index.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    <div class="page-title">
        <div class="pull-left">
            <h3>  List Products</h3>
        </div>




        <div class="pull-right">
            <a href="{{url('/product/create')}}" class="btn btn-primary pull-right">Add New Product</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

    @if(Session::has('product'))
        <div class="col-md-12" id="status">
            <div class="alert alert-success text-center">
                {{Session::get('product')}}
            </div>

        </div>

    @endif


    <div class="">


        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        {{--<h2>Supplier: {{$supplier->supplier_name}}</h2>--}}
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable-product" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>SN</th>

                                <th> Product Name</th>
                               
                                <th>Status</th>
                                <th>Action(s)</th>

                            </tr>
                            </thead>
                            <tbody>
                            <?php $a = 1 ?>
                            @foreach($products as $product)
                                <tr>
                                    <td><?= $a ?></td>

                                    <td>{{$product->name}}</td>
                                    
                                    <td>
                                        @if($product->status==1)
                                            <span class="label label-success">Active</span>
                                        @else
                                            <span class="label label-danger">Inactive</span>
                                        @endif
                                    </td>


                                    <td>
                                        <a href="{{url('product/'.$product->id.'/edit')}}" title="Edit" class="btn btn-xs btn-info pull-left"> <i class="fa fa-edit"> </i></a>
                                        @if($product->status==0)
                                            @if(count($product->invoiceDetails)==0)
                                            <form action="{{url('product/'.$product->id)}}" method="POST" class="pull-left">
                                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('{{\App\Constant\Constant::DELETE_SOFT}}')"><i class="fa fa-trash-o" title="Delete"></i></button>
                                            </form>
                                            @endif
                                        @endif
                                        @if($product->status==0)
                                            <a href="{{url('product/p-enable/'.$product->id)}}" class="btn btn-xs btn-primary pull-left" onclick="return confirm('{{\App\Constant\Constant::ACTIVATE}}')"><i class="fa fa-check" title="Enable product Method"></i></a>
                                        @endif
                                        @if ($product->status==1)
                                            <a href="{{url('product/p-disable/'.$product->id)}}" class="btn btn-xs btn-warning pull-left"  onclick="return confirm('{{\App\Constant\Constant::DE_ACTIVATE}}')"> <i class="fa fa-warning" title="Disable product Method"></i></a>
                                        @endif

                                        <div class="clearfix"></div>
                                    </td>
                                    <div class="clearfix"></div>
                                </tr>
                                <?php $a = 1 + $a ?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
@section('custom-scripts')
    <script>
        $("#datatable-product").dataTable({});

    </script>
@endsection


@stop