routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



Auth::routes();

Route::get('/home', function(){
    return redirect('/');
});
Route::group(['middleware'=>['auth']],function(){
    Route::get('/', 'Admin\DashboardController@index');
    Route::get('/dashboard', 'Admin\DashboardController@index');

    /*
     * Sagar
     **/

    Route::resource('/customer','Admin\CustomerController');//customer's main page
    Route::get('/forcedeletecustomer/{customerid}','Admin\CustomerController@forcedeletecustomer');//customer's hard delete
    Route::get('/deletedcustomers','Admin\CustomerController@deletedCustomer');//customer deleted list page
    Route::get('/restorecustomer/{customerid}','Admin\CustomerController@restoreCustomer');//restoreing the deleted data using id from restore page to index page

    /*
     * end sagar code
     **/


    /*
     * rojina
     **/

    Route::resource('/supplier','Admin\SupplierController');//displays supplier's landing page

    /* Payment started*/
    Route::resource('/payment','Admin\PaymentController');//displays payment landing page

    Route::get('/payment/add/{supplier}','Admin\PaymentController@addInfo');// For listingform  regarding payment method based on supplier_id

    Route::get('/payment/mtdenable/{supplier}','Admin\PaymentController@mtdEnable');// For listing enabling payment method by passing supplier's id

    Route::get('/deletedpayment/{supplier}','Admin\PaymentController@deletedPayMethod');// For  listing temporarily deleted  payment method of the given supplier

    Route::get('/restorepayment/{paymentid}','Admin\PaymentController@restorePayMethod');//To  listing restored  payment method details once deleted//

    Route::get('/forcedeletepaymtd/{paymentid}','Admin\PaymentController@forceDelete');//To delete the payment method that is soft deleted once

    /* Payment ended*/
    /*Invoice start*/

    Route::resource('/invoice','Admin\InvoiceController');//displays invoice's landing page
    Route::get('/deletedinvoices','Admin\InvoiceController@deletedInvoices');//invoice deleted page
    Route::get('/deletedinvoicesinformation/{invoiceid}','Admin\InvoiceController@showdeletedInvoice');//Invoice deleted detail page
    Route::get('/restoredeletedinvoice/{invoiceid}','Admin\InvoiceController@restoreDeletedInvoice');//To restore deleted invoice
    Route::get('/forcedeletedinvoice/{invoiceid}','Admin\InvoiceController@forceDeleted');//To delete invoice permanently
    Route::get('/paidinvoices','Admin\InvoiceController@index');

    /*Invoice ended*/

    /*Product started*/
    Route::resource('/product','Admin\ProductController');//displays product main page
    Route::get('/deletedproducts','Admin\ProductController@deletedProduct');//product deleted page
    Route::get('/restoreproduct/{productid}','Admin\ProductController@restoreProduct');//For restoring the deleted products soft deleted  before
    Route::delete('/forcedeletedproduct/{productid}','Admin\ProductController@forceDelete');//For deleting product permanently
    Route::get('/product/p-enable/{productid}','Admin\ProductController@productEnable');//To enable product status that was disabled before
    Route::get('/product/p-disable/{productid}','Admin\ProductController@productDisable');//To disable product status that was enabled before

    /*Product ended*/

    /*Payamount Started*/
    Route::resource('/payamount','Admin\PayamountController');
    Route::get('/addpayamount/{invoiceid}','Admin\PayamountController@enterAmount');


    /* print invoice */
    Route::get('print-invoice/{invoiceid}', "Admin\InvoiceController@printInvoice");

    /*pdf generator*/
    Route::get('/downloadpdf/{invoiceid}',"Admin\InvoiceController@generatePdf");
    Route::get('/invoice-sendmail/{invoiceid}',"Admin\InvoiceController@sendInvoiceMail");//send mail with invoice pdf attached

    Route::get('/changepassword','Admin\DashboardController@changePassword');
    Route::post('/updatepassword','Admin\DashboardController@updatePassword')->name('password.update');

    /*
     * end rojina code
     * */



});

resources/views/admin/partials/css.blade.php
<!-- Bootstrap -->
<link href="{{asset('bootstrap/dist/css/bootstrap.min.css')}}"rel="stylesheet">
<!-- Font Awesome -->
<link href="{{asset('font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
<link href="{{asset('/magnific-popup/magnific-popup.css')}}" rel="stylesheet">
<link href="{{asset('/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet">
<!-- Custom styling plus plugins -->
<link href="{{asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('build/css/custom.css')}}" rel="stylesheet">

resources/views/admin/partials/leftnav.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <img src="{{asset('images/logo/user.png')}}" alt="{{Auth::user()->name}}" class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{Auth::user()->name}}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        {{--<br />--}}

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{url('/')}}"><i class="fa fa-home"></i> Dashboard </a>
                    </li>
                    <li><a><i class="fa fa-user-plus"></i>Suppliers <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('supplier.create')}}">Add Supplier</a></li>
                            <li><a href="{{route('supplier.index')}}">List Suppliers</a></li>
                        </ul>
                    </li>

                    <li><a><i class="fa fa-user"></i>Customers <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('customer.create')}}">Add Customer</a></li>
                            <li><a href="{{route('customer.index')}}">List Customers</a></li>
                        </ul>
                    </li>

                    <li><a><i class="fa fa-product-hunt"></i>Products <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('product.create')}}">Add products</a></li>
                            <li><a href="{{route('product.index')}}">List Products</a></li>
                        </ul>
                    </li>
                    {{--<li><a><i class="fa fa-money"></i>Payment <span class="fa fa-chevron-down"></span></a>--}}
                        {{--<ul class="nav child_menu">--}}
                            {{--<li><a href="{{route('payment.create')}}">Add Payment</a></li>--}}
                            {{--<li><a href="{{route('payment.index')}}">List Payment</a></li>--}}
                        {{--</ul>--}}
                    {{--</li>--}}

                    <li> <a><i class="fa fa-file-excel-o"> </i>Invoice <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('invoice.create')}}"> Add Invoice</a></li>
                            <li><a href="{{route('invoice.index')}}">List Invoice</a></li>

                        </ul>

                    </li>


                    <li><a><i class="fa fa-trash"></i>Trash <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{url('deletedcustomers')}}">Deleted Customers</a></li>
                            <li><a href="{{url('deletedproducts')}}">Deleted Products</a></li>
                            <li><a href="{{url('deletedinvoices')}}">Deleted Invoice</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{url('/changepassword')}}"><i class="fa fa-key"></i>Change Password</a>
                    </li>

                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

resources/views/admin/partials/scripts.blade.php
<!-- jQuery -->
<script src="{{asset('jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{asset('bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('moment/moment.min.js')}}"></script>
<script src="{{asset('vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('magnific-popup/jquery.magnific-popup.min.js')}}"></script>



<!-- Custom Theme Scripts -->
<script src="{{asset('build/js/custom.js')}}"></script>

<script>
    $(document).ready(function(){
        


    });
</script>

@yield('custom-script')

resources/views/admin/partials/topnavbar.blade.php
<div class="top_nav">


    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{{ url('/logout')}}" onclick="event.preventDefault();
                                                       document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i>
                        <span class="hidden-xs">
                                Logout
                        </span>
                    </a>
                    <form id="logout-form" action="{{ url('/logout')}}" method="POST" style="display: none;">
                        {{ csrf_field()}}
                    </form>

                </li>

            </ul>
        </nav>
    </div>
</div>