routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



Auth::routes();

Route::get('/home', function(){
    return redirect('/');
});
Route::group(['middleware'=>['auth']],function(){
    Route::get('/', 'Admin\DashboardController@index');
    Route::get('/dashboard', 'Admin\DashboardController@index');

    /*
     * Sagar
     **/

    Route::resource('/customer','Admin\CustomerController');//customer's main page
    Route::get('/forcedeletecustomer/{customerid}','Admin\CustomerController@forcedeletecustomer');//customer's hard delete
    Route::get('/deletedcustomers','Admin\CustomerController@deletedCustomer');//customer deleted list page
    Route::get('/restorecustomer/{customerid}','Admin\CustomerController@restoreCustomer');//restoreing the deleted data using id from restore page to index page

    /*
     * end sagar code
     **/


    /*
     * rojina
     **/

    Route::resource('/supplier','Admin\SupplierController');//displays supplier's landing page

    /* Payment started*/
    Route::resource('/payment','Admin\PaymentController');//displays payment landing page

    Route::get('/payment/add/{supplier}','Admin\PaymentController@addInfo');// For listingform  regarding payment method based on supplier_id

    Route::get('/payment/mtdenable/{supplier}','Admin\PaymentController@mtdEnable');// For listing enabling payment method by passing supplier's id

    Route::get('/deletedpayment/{supplier}','Admin\PaymentController@deletedPayMethod');// For  listing temporarily deleted  payment method of the given supplier

    Route::get('/restorepayment/{paymentid}','Admin\PaymentController@restorePayMethod');//To  listing restored  payment method details once deleted//

    Route::get('/forcedeletepaymtd/{paymentid}','Admin\PaymentController@forceDelete');//To delete the payment method that is soft deleted once

    /* Payment ended*/
    /*Invoice start*/

    Route::resource('/invoice','Admin\InvoiceController');//displays invoice's landing page
    Route::get('/deletedinvoices','Admin\InvoiceController@deletedInvoices');//invoice deleted page
    Route::get('/deletedinvoicesinformation/{invoiceid}','Admin\InvoiceController@showdeletedInvoice');//Invoice deleted detail page
    Route::get('/restoredeletedinvoice/{invoiceid}','Admin\InvoiceController@restoreDeletedInvoice');//To restore deleted invoice
    Route::get('/forcedeletedinvoice/{invoiceid}','Admin\InvoiceController@forceDeleted');//To delete invoice permanently
    Route::get('/paidinvoices','Admin\InvoiceController@index');

    /*Invoice ended*/

    /*Product started*/
    Route::resource('/product','Admin\ProductController');//displays product main page
    Route::get('/deletedproducts','Admin\ProductController@deletedProduct');//product deleted page
    Route::get('/restoreproduct/{productid}','Admin\ProductController@restoreProduct');//For restoring the deleted products soft deleted  before
    Route::delete('/forcedeletedproduct/{productid}','Admin\ProductController@forceDelete');//For deleting product permanently
    Route::get('/product/p-enable/{productid}','Admin\ProductController@productEnable');//To enable product status that was disabled before
    Route::get('/product/p-disable/{productid}','Admin\ProductController@productDisable');//To disable product status that was enabled before

    /*Product ended*/

    /*Payamount Started*/
    Route::resource('/payamount','Admin\PayamountController');
    Route::get('/addpayamount/{invoiceid}','Admin\PayamountController@enterAmount');


    /* print invoice */
    Route::get('print-invoice/{invoiceid}', "Admin\InvoiceController@printInvoice");

    /*pdf generator*/
    Route::get('/downloadpdf/{invoiceid}',"Admin\InvoiceController@generatePdf");
    Route::get('/invoice-sendmail/{invoiceid}',"Admin\InvoiceController@sendInvoiceMail");//send mail with invoice pdf attached

    Route::get('/changepassword','Admin\DashboardController@changePassword');
    Route::post('/updatepassword','Admin\DashboardController@updatePassword')->name('password.update');

    /*
     * end rojina code
     * */



});

app/Http/Controllers/Admin/PaymentController.php
<?php

namespace App\Http\Controllers\Admin;
/*
 * Code By: Rojina
 * Date: 10 aug 2017
 * */
use App\Http\Requests\PaymentRequest;
use App\Model\Payment;
use App\Model\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;


class PaymentController extends Controller
{
    /**
     * Display a list of the supplier's payment methods.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $payments=Payment:: OrderBy('id','DESC')->get();
//        return view('admin.payment.index')
//            ->with('payments',$payments);

    }
//
    /**
     * Show the form for creating a new payment method.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.payment.create');
    }

    /**
     * Store a newly created payment in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PaymentRequest $request)
    {
        $payment=Payment::create(Input::all());
        $payment->save();
        Payment::where('id','!=',$payment->id)->update(['status'=>0]);
        Session::flash('payment','New Payment Method Added Successfully');
        return redirect('/payment/'.Input::get('supplier_id'));

    }
    /*
     * Creating form  regarding payment method based on supplier_id
     *@param int $supplier
     * @@return \Illuminate\Http\Response
     *
     *
     */

    public function addInfo($supplier_id)
    {
        $supplier = Supplier::where('id', $supplier_id)->first();
        return view('admin.payment.create')
            ->with('supplier', $supplier);
    }

    /**
     * Display the specified payment method for specified supplier.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     * @param int $supplier
     */
    public function show($supplier_id)
    {
        $supplier =Supplier::where('id',$supplier_id)->first();
        $payments=Payment::where('supplier_id',$supplier_id)->orderBy('id','DESC')->get();
        return view('admin.payment.index')
            ->with('payments',$payments)
            ->with('supplier',$supplier);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $payment=Payment::where('id',$id)->first();
        $supplier=Supplier::where('id',$payment->supplier_id)->first();
        return view('admin.payment.edit')
            ->with('payment',$payment)
            ->with('supplier',$supplier);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PaymentRequest $request, $id)
    {
        $payment=Payment::find($id);
//        $supplier=Supplier::where('id',$payment->supplier_id)->first();
        $payment->update(Input::all());
        $payment->save();
        Session()->flash('payment',"Updated Payment Method Successfully");
        return redirect('/payment/'.$payment->supplier_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $payment=Payment::find($id);

        $payment->delete();
        Session()->flash('payment',"Deleted Payment Method Successfully");
        return redirect('/deletedpayment/'.$payment->supplier_id);

    }

    public function mtdEnable($p_mtd_id){
        $payment=Payment::find($p_mtd_id);
        $payment->status=1;
        $payment->save();
        Payment::where('id','!=',$p_mtd_id)->update(['status'=>0]);
        Session()->flash('payment',"Choosen Payment Method Activated Successfully");
        return redirect('/payment/'.$payment->supplier_id);

    }
    /*
     *
     * Supplying supplierid and deleting Payment methods from the associated suppliers
     */

    public function deletedPayMethod($supplierid){
        $payments=Payment::where('supplier_id',$supplierid)->onlyTrashed()->get();
        $supplier=Supplier::where('id',$supplierid)->first();
        return view('admin.payment.deleted', compact('payments','supplier'));
    }
    /*
     *
     *
     * For restoring the payment methods once deleted
     */
    public function restorePayMethod($p_mtd_id)
    {
        $payment=Payment::onlyTrashed()->find($p_mtd_id);
        $payment->restore();
        Session()->flash('payment',"Restore Payment Method Successfully");
        return redirect('/deletedpayment/'.$payment->supplier_id);
    }

    /*
     *
     *
     * For deleting the payment methods permanantly
     */
    public function forceDelete($p_mtd_id)
    {
        $payment=Payment::onlyTrashed()->find($p_mtd_id);
        $payment->forceDelete();
        Session()->flash('payment',"Payment Method Permanently Deleted Successfully!!!!");
        return redirect('/deletedpayment/'.$payment->supplier_id);
    }
}

resources/views/admin/payment/create.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')


    <div class="page-title">
        <div class="title_left">
            <h3>Add New Payment Method</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if(\Illuminate\Support\Facades\Session::has('payment'))
        <div class="alert alert-danger" id="status">
            {{\Illuminate\Support\Facades\Session::get('payment')}}
        </div>
    @endif

    <form class="form-horizontal form-label-left" action="{{route('payment.store')}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Payment Details</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <input type="hidden" class="form-control" name="supplier_id" value="{{$supplier->id}}">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Supplier Name:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="supplier_name" data-inputmask="'mask': '99/99/9999'" disabled value="{{$supplier->supplier_name}}">
                                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Bank Name *:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="bank_name" data-inputmask="'mask': '99/99/9999'" value="{{old('bank_name')}}" required>
                                <span class="fa fa-bank form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">BSB *:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="bsb" data-inputmask="'mask': '99/99/9999'" value="{{old('bsb')}}" required>
                                <span class="fa fa-info form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Account Number *:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="account_no" data-inputmask="'mask': '99/99/9999'"  value="{{old('account_no')}}"required>
                                <span class="fa fa-book form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Payment Method *:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="pay_method" data-inputmask="'mask': '99/99/9999'" value="{{old('pay_method')}}" required>
                                <span class="fa fa-external-link form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>



                    </div>
                </div>
                <div class="x_panel">
                    <div class="x_content">

                        <div class="col-md-12 col-sm-9 col-xs-12 " align="center">
                            <button type="submit" class="btn btn-success">Submit</button>

                            <button type="reset" class="btn btn-default">Reset</button>

                            <a href="{{url('/payment/'.$supplier->id)}}" class="btn btn-danger">Cancel</a>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </form>



@stop

resources/views/admin/payment/deleted.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    <div class="page-title">
        <div class="pull-left">
            <h3>Deleted Payment Method</h3>
        </div>




        <div class="pull-right">
            <a href="{{url('/payment/'.$supplier->id)}}" class="btn btn-primary pull-right">List Payment Methods</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

    @if(\Illuminate\Support\Facades\Session::has('payment'))
        <div class="col-md-12" id="status">

            <div class="alert alert-success text-center">
                {{\Illuminate\Support\Facades\Session::get('payment')}}
            </div>

        </div>

    @endif


    <div class="">


        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Supplier: {{$supplier->supplier_name}}</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>ID</th>

                                <th> Bank Name</th>
                                <th> BSB</th>
                                <th>Account Number</th>
                                <th>Action(s)</th>

                            </tr>
                            </thead>


                            <tbody>
                            <?php $a = 1 ?>
                            @foreach($payments as $payment)
                                <tr>
                                    <td><?= $a ?></td>

                                    <td>{{$payment->bank_name}}</td>
                                    <td>{{$payment->bsb}}</td>
                                    <td>{{$payment->account_no}}</td>
                                    <td>
                                        <a href="{{url('/restorepayment/'.$payment->id)}}" title="Restore Payment Method" class="btn btn-xs btn-default"> <i class="fa fa-undo"> </i></a>
                                        <a href="{{url('/forcedeletepaymtd/'.$payment->id)}}" title="Delete Permanently" class="btn btn-xs btn-danger" onclick="return confirm('Are You Sure??')"> <i class="fa fa-trash-o"> </i></a>
                                    </td>

                                </tr>
                                <?php $a = 1 + $a ?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>


@stop

resources/views/admin/payment/edit.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')


    <div class="page-title">
        <div class="title_left">
            <h3>Edit Payment Method Information</h3>
        </div>
    </div>

    <form class="form-horizontal form-label-left" action="{{route('payment.update',[$payment->id])}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}

        <input type="hidden" name="_method" value="PATCH">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Payment Details</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <input type="hidden" class="form-control" name="supplier_id" value="{{$supplier->id}}">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Supplier Name:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="bank_name" data-inputmask="'mask': '99/99/9999'" disabled value="{{$supplier->supplier_name}}">
                                <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Bank Name *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="bank_name" data-inputmask="'mask': '99/99/9999'" value="{{$payment->bank_name}}" required>
                                <span class="fa fa-bank form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">BSB *</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="bsb" data-inputmask="'mask': '99/99/9999'" value="{{$payment->bsb}}" required>
                                <span class="fa fa-info form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6">Account Number </label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="account_no" data-inputmask="'mask': '99/99/9999'" value="{{$payment->account_no}}" required>
                                <span class="fa fa-book form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-6 col-xs-6"> Payment Method *:</label>
                            <div class="col-md-8 col-sm-8 col-xs-6">
                                <input type="text" class="form-control" name="pay_method" data-inputmask="'mask': '99/99/9999'"  value="{{$payment->pay_method}}"required>
                                <span class="fa fa-external-link form-control-feedback right" aria-hidden="true"></span>
                            </div>
                        </div>



                    </div>
                </div>
                <div class="x_panel">
                    <div class="x_content">

                        <div class="col-md-12 col-sm-9 col-xs-12 " align="center">
                            <button type="submit" class="btn btn-success">Submit</button>

                            <button type="reset" class="btn btn-default">Reset</button>

                            <a href="{{url('/payment/'.$supplier->id)}}" class="btn btn-danger">Cancel</a>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </form>

@stop

resources/views/admin/payment/index.blade.php
@extends('admin.baselayout.baselayout')
@section('main-content')
    <div class="page-title">
        <div class="pull-left">
            <h3>Payment Method</h3>
        </div>




        <div class="pull-right">
            <a href="{{url('/payment/add/'.$supplier->id)}}" class="btn btn-primary pull-right">Add Payment Method</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

        @if(\Illuminate\Support\Facades\Session::has('payment'))
        <div class="col-md-12" id="status">

            <div class="alert alert-success text-center">
                {{\Illuminate\Support\Facades\Session::get('payment')}}
            </div>

        </div>

        @endif


    <div class="">


        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Supplier: {{$supplier->supplier_name}}</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>SN</th>

                                <th>Bank Name</th>
                                <th>BSB</th>
                                <th>Account Number</th>
                                <th>Pay Method</th>
                                <th>Status</th>
                                <th>Action(s)</th>

                            </tr>
                            </thead>


                            <tbody>
                            <?php $a = 1 ?>
                            @foreach($payments as $payment)
                                <tr>
                                    <td><?= $a ?></td>

                                    <td>{{$payment->bank_name}}</td>
                                    <td>{{$payment->bsb}}</td>
                                    <td>{{$payment->account_no}}</td>
                                    <td>{{$payment->pay_method}}</td>
                                    <td>
                                        @if($payment->status==1)
                                            <span class="label label-success">Active</span>
                                        @else
                                            <span class="label label-danger">Inactive</span>
                                        @endif
                                    </td>

                                    <td>
                                        <a href="{{url('payment/'.$payment->id.'/edit')}}" title="Edit" class="btn btn-xs btn-info pull-left"> <i class="fa fa-pencil"> </i></a>
                                        @if($payment->status==0)
                                            <form action="{{url('payment/'.$payment->id)}}" method="POST" class="pull-left">
                                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('Are You Sure??')"><i class="fa fa-trash-o" title="Delete"></i></button>
                                            </form>
                                        @endif
                                        @if($payment->status==0)
                                            <a href="{{url('payment/mtdenable/'.$payment->id)}}" class="btn btn-xs btn-primary pull-left"><i class="fa fa-check" title="Enable Payment Method"></i></a>
                                        @endif
                                        <div class="clearfix"></div>
                                    </td>
                                    <div class="clearfix"></div>
                                </tr>
                                <?php $a = 1 + $a ?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>


@stop